mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fkream
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db_sql/schema.sql
# 테스트시는 이것을 빼야 돌아간다. 있으면 에러걸림
#      data-locations:
#        - classpath:db_sql/data.sql

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace