mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db_sql/schema.sql
      data-locations:
        - classpath:db_sql/data.sql
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  redis:
    cache:
      host: ${REDIS_CACHE_HOST}
      port: ${REDIS_CACHE_PORT}
    session:
      host: ${REDIS_SESSION_HOST}
      port: ${REDIS_SESSION_PORT}
    timeout: 30000
  session:
    store-type: redis
  cache:
    type: redis

logging.level:
  org.hibernate.SQL: debug
