mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles:
    active: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: fkream
      username: admin
      password: admin
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driverClassName: com.mysql.cj.jdbc.Driver
    master:
      hikari:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}
        read-only: false
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    slave:
      hikari:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://49.50.161.215:3306/fkream
        read-only: true
        username: root
        password: root
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db_sql/schema.sql
      data-locations:
        - classpath:db_sql/data.sql
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  redis:
    cache:
      host: ${REDIS_CACHE_HOST}
      port: ${REDIS_CACHE_PORT}
    session:
      host: ${REDIS_SESSION_HOST}
      port: ${REDIS_SESSION_PORT}
    redisson:
      host: ${REDIS_SESSION_HOST}
      port: 6381
    timeout: 30000

logging.level:
  org.hibernate.SQL: debug

pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  reasonable: true
