mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles:
    active: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: fkream
      username: admin
      password: admin
      auto-index-creation: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db_sql/schema.sql
      data-locations:
        - classpath:db_sql/data.sql
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  redis:
    cache:
      host: ${REDIS_CACHE_HOST}
      port: ${REDIS_CACHE_PORT}
    session:
      host: ${REDIS_SESSION_HOST}
      port: ${REDIS_SESSION_PORT}
    redisson:
      host: ${REDIS_SESSION_HOST}
      port: 6381
    timeout: 30000
  kafka:
    bootstrap-servers: 101.101.210.178:9092, 101.101.210.178:9093, 101.101.210.178:9094
  elasticsearch:
    uris: 101.101.210.178:9200

logging.level:
  org.hibernate.SQL: debug

pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  reasonable: true

#################################################################################

datasource:
  property:
    shards:
      - master:
          url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}
          username: ${DB_USERNAME}
          password: ${DB_PASSWORD}
          name: master1
        slave:
          url: jdbc:mysql://49.50.161.215:3306/fkream
          username: root
          password: root
          name: slave1
      - master:
          url: jdbc:mysql://${MYSQL_HOST}:3307/${DB_NAME}
          username: root
          password: root
          name: master2
        slave:
          url: jdbc:mysql://49.50.161.215:3307/fkream
          username: root
          password: root
          name: slave2

sharding:
  address:
    strategy: RANGE
    rules:
      - shard_no: 0
        range_min: 0
        range_max: 100

      - shard_no: 1
        range_min: 101
        range_max: 200 #최댓값을 안했다.

