spring:
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db_sql/testSchema.sql
      data-locations:
        - classpath:db_sql/data.sql
  redis:
    cache:
      host: ${REDIS_CACHE_HOST}
      port: ${REDIS_CACHE_PORT}
    session:
      host: ${REDIS_SESSION_HOST}
      port: ${REDIS_SESSION_PORT}